name: 15d986da-2d7c-44fb-af71-700494485def
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - jupyter
  - intake
  - intake-xarray
  - rasterio
  - opencv
  - geopandas
  - tqdm
  - hvplot
  - datashader
  - pooch
  - xmltodict