name: 15d986da-2d7c-44fb-af71-700494485def
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - jupyter
  - intake
  - intake-xarray
  - rasterio
  - opencv
  - geopandas
  - tqdm
  - geoviews
  - hvplot
  - datashader
  - pooch
  - xmltodict
  - scikit-image
  - deepforest
  - pip
  - pip:
      - albumentations==2.0.6